# Default values for hello-app helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
 
replicaCount: 1
namespace: default
 
image:
 repository: gcr.io/anthos-alpha-5929/hello-application
 tag: latest
 pullPolicy: Always
 
deployment:
 
application:
 readinessInitialDelaySeconds: 60
 readinessPeriodSeconds: 10
 healthCheck: /swagger/
 containerPort: 8080
 
service:
 type: LoadBalancer
 port: 8080
 javaOPTS: -Xms128m -Xmx256m
 externalPort: 8080
 internalPort: 8080
 
hpa:
 maxReplicas: 3
 minReplicas: 1
 targetCPUUtilizationPercentage: 70
 
resources:
 limits:
   cpu: 1000m
   memory: 2048Mi
 requests:
   cpu: 400m
   memory: 1024Mi


